### ISSUE TITLE
Bug: Hugging Face hub authentication

### ISSUE THREAD

**Issue by bergr7** [flowritecom/flow-merge#20]
# 🐛 Bug report

## **Summary**

Currently, the library does not log the user into HF hub even if the token is passed in the config.yaml.

## **Actual Behavior**

If a gated or privated model is passed in the models list, the load config function errors out:
```
flow-merge run --config ./biomistral/slerp_config.yaml --model_name biomistral_slerp_7b
flow_merge.lib.merge_runner - INFO - Starting merge...
flow_merge.lib.merge_runner - ERROR - Merge error: RuntimeError - Failed to load config for model mistralai/Mistral-7B-Instruct-v0.2
```

The error message could be improve too..

Tried to load the model manually and this was the actual error from transformers library:

```
...
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/envs/flow-merge/lib/python3.10/site-packages/transformers/configuration_utils.py", line 688, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/envs/flow-merge/lib/python3.10/site-packages/transformers/utils/hub.py", line 416, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2.
401 Client Error. (Request ID: Root=1-662e549f-06bec9942e4a5164323cb0d1;498fe681-a1ee-4564-94c3-04a3098285df)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must be authenticated to access it.
```

## **Expected behavior**

If hf token is passed, the user should be logged in.

## **To Reproduce**
Merge configuration file (if relevant):
```yaml
method: slerp
method_global_parameters:
  t: 0.5
base_model: BioMistral/BioMistral-7B
models:
  - model: BioMistral/BioMistral-7B
  - model: mistralai/Mistral-7B-Instruct-v0.2
tokenizer:
  mode: base
  interpolation_method: linear
directory_settings:
  output_dir: ./biomistral/biomistral_slerp_7b/
hf_token:
  token: <your_token>
  trust_remote_code: True
device: cpu
```

1. Create the config file above
2. Run `flow-merge run --config <path_to_file> --model_name model`

## **Environment**

- OS: Ubuntu 22.04.4 LTS
- Python version:Python 3.10.13
- Library version: 0.1.0
- Other relevant dependencies: NA
