### ISSUE TITLE
Improve validation error messages for better user experience and fix some logic

### ISSUE THREAD

**Issue by bergr7** [flowritecom/flow-merge#6]
# Description
The current validation error messages in the `flow-merge validate --config ...` tool could be improved to provide a better user experience. When a user encounters a validation error, the message should clearly explain what went wrong and provide actionable steps to resolve the issue.

For example, the current error message for a missing required field in the configuration file looks like this:

```
Configuration file is invalid: 1 validation error for ValidatedInputData
models.0.model
  Field required [type=missing, input_value={'models': 'TheBloke/Llama-2-13B-fp16'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

An improved error message could start with:

```
Error: Missing required field '<name_of_field>' in the configuration file.

...

Example of a correct model entry:
models:
  - model: TheBloke/Llama-2-13B-fp16
    weight:
    
...
```

Also note in the example above, it seems the validate command it complaining about the missing weight for the base_model. Weights should be optional. See config below to reproduce:

```yaml
method: addition-task-arithmetic
method_global_parameters:
  scaling_coefficient: 0.8
  normalize: False
base_model: TheBloke/Llama-2-13B-fp16
models:
  - models: TheBloke/Llama-2-13B-fp16
  - model: Undi95/UtopiaXL-13B
    weight: 1.0
  - model: Doctor-Shotgun/cat-v1.0-13b
    weight: 0.4
  - model: PygmalionAI/mythalion-13b
    weight: 0.3
  - model: KoboldAI/LLaMA2-13B-Tiefighter
    weight: 0.2
tokenizer:
  mode: base
  interpolation_method: linear
directory_settings:
  cache_dir: null
  local_dir: ./models
  output_dir: ./flow_estopia_13B
hf_hub_settings:
  token: null
  trust_remote_code: False
device: cpu
```
